'''
Field index in tables of DB
'''
# INSERT ID
INSERT_ID = 0

# Table users
USERS_USER_ID = 0
USERS_USER_USERNAME = 1
USERS_USER_PASSWORD = 2

# Table user_plan
USER_PLAN_USER_ID = 0
USER_PLAN_PLAN_ID = 1
USER_PLAN_START_TIME = 2
USER_PLAN_END_TIME = 3
USER_PLAN_PLAN_NAME = 4

# Table app_screen_time
APP_SCREEN_TIME_ID = 0
APP_SCREEN_START_TIME = 1
APP_SCREEN_END_TIME = 2
APP_SCREEN_APP_NAME = 3

# Table app_notification
APP_NOTIFICATION_NOTIFICATION_ID = 0
APP_NOTIFICATION_NOTIFICATION_TIME = 1
APP_NOTIFICATION_NOTIFICATION_TYPE = 2
APP_NOTIFICATION_APP_NAME = 3


